# Generated by Django 2.0.5 on 2018-05-15 20:17

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('dashboard', '0074_auto_20180515_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='keywords',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='account.TaggedKeyword', to='account.Keyword', verbose_name='Tags'),
        ),
    ]
